# docker-compose.yml

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    networks:
      valhalla-network:
        ipv4_address: 172.20.0.2
    volumes:
      - projectvalhalla_data:/usr/src/ProjectValhalla
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  db:
    build:
      context: .
      dockerfile: dockerfile.pq
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      valhalla-network:
        ipv4_address: 172.20.0.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
  valhalla-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  db-data:
  projectvalhalla_data:
