version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: dockerfile.pq
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      valhalla_network:
        ipv4_address: 172.20.0.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    build:
      context: .
      dockerfile: dockerfile.api
    networks:
      valhalla_network:
        ipv4_address: 172.20.0.2
    volumes:
      - src_data:/usr/src/
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "18080:80"

networks:
  valhalla_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  db_data:
  src_data:
